apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: yolo
  name: yolo
spec:
  replicas: 0
  selector:
    name: yolo
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: yolo
        name: yolo
    spec:
      containers:
        - image: 'docker.io/willb/imagescorer:latest'
          imagePullPolicy: Always
          name: yolo
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /v2/ui/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "3"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30  
  triggers:
    - type: ConfigChange
