apiVersion: v1
kind: Service
metadata:
  labels:
    app: yolo
    name: yolo
  name: yolo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: yolo
  type: ClusterIP